#!/usr/bin/env bash
# Displays numbers from 1 to 100 with "Fizz", "Buzz", or "FizzBuzz" for multiples of 3, 5, and 15, respectively.

COUNTER=1
while [ "$COUNTER" -lt 101 ]; do
    if [ $((COUNTER % 15)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((COUNTER % 3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((COUNTER % 5)) -eq 0 ]; then
        echo "Buzz"
    else
        echo "$COUNTER"
    fi
    ((COUNTER++))
done

# Exit the script after the loop completes
exit 0
