#!/usr/bin/env bash
# Displays numbers from 1 to 20 with special messages for certain numbers.

COUNTER=1
while [ "$COUNTER" -lt 21 ]; do
    case "$COUNTER" in
        4)
            echo "$COUNTER"
            echo "bad luck from China"
            ;;
        9)
            echo "$COUNTER"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$COUNTER"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$COUNTER"
            ;;
    esac

    ((COUNTER++))
done

# Exit the script after the loop completes
exit 0
